name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Nods.js envoironment
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 20.17.0
        
      - name: E2E Testes
        uses: cypress-io/github-action@v6 

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v3.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: SonarCloud Summary Action
        uses: thecanadianroot/sonarcloud-summary-action@v1
        with:
          github-repository: ${{ github.repository }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pull-request: ${{ github.event.pull_request.number }} 
