name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Nods.js envoironment
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 20.17.0
        
      - name: Cypress run
        run: | 
          npm install cypress
          npx cypress open        
        
          
      - name: Save build folder
        uses: actions/upload-artifact@v4
        with:
          name: build
          if-no-files-found: error
          path: dist
