name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Nods.js envoironment
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 20.17.0
        
      - name: E2E Testes
        uses: cypress-io/github-action@v6 
