name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Nods.js envoironment
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 20.17.0
          
      - name: Install CTRF
        uses: github-actions-ctrf@0.0.49
        
      - name: E2E Testes
        uses: cypress-io/github-action@v6 

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v3.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Publish CTRF Test Summary Results
        run: npx github-actions-ctrf summary ctrf-ctrf-report.json
        if: always()
